### ISSUE TITLE
Exposing subgroup ops for unsupported shader stages

### ISSUE THREAD

**Issue by Joshua-Ashton** [GPUOpen-Drivers/xgl#103]
The Vulkan spec states:
```
supportedStages is a bitfield of VkShaderStageFlagBits describing the shader stages that group
operations with subgroup scope are supported in. supportedStages will have the
VK_SHADER_STAGE_COMPUTE_BIT bit set if any of the physical device’s
queues support VK_QUEUE_COMPUTE_BIT.
```

This is exposed for a wide variety of unsupported ray-tracing related shader stages
```c
                            VK_SHADER_STAGE_RAYGEN_BIT_KHR
                            VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR
                            VK_SHADER_STAGE_MISS_BIT_KHR
                            VK_SHADER_STAGE_INTERSECTION_BIT_KHR
                            VK_SHADER_STAGE_CALLABLE_BIT_KHR
```
despite these shader stages not being supported at all.

https://github.com/GPUOpen-Drivers/xgl/blob/e5c5ad454049892ed803b0adcc15ef6fb27ec50e/icd/api/vk_physical_device.cpp#L4168

Therefore, these shader stages do not support these subgroup operations and they should not be exposed here.

**Comment by qiaojbao** [comment]
Good catch, we will fix it. Thanks.
