### ISSUE TITLE
Invalid unit in VkPipelineCreationFeedbackEXT::duration on Windows

### ISSUE THREAD

**Issue by RuslanKutdusov** [GPUOpen-Drivers/xgl#106]
Hi, we've encountered that vkCreateGraphicsPipelines/vkCreateComputePipelines return in VkPipelineCreationFeedbackEXT::duration number of cpu ticks instead of nanoseconds on Windows. By specification, VkPipelineCreationFeedbackEXT::duration is the duration spent creating a pipeline or pipeline stage in nanoseconds.

**Comment by jinjianrong** [comment]
This is fixed in latest code: 
https://github.com/GPUOpen-Drivers/xgl/blob/8bf20dd1ca8b6b773ff0a773c09a845a9be42a96/icd/api/vk_graphics_pipeline.cpp#L969

https://github.com/GPUOpen-Drivers/xgl/blob/8bf20dd1ca8b6b773ff0a773c09a845a9be42a96/icd/api/vk_compute_pipeline.cpp#L618
