### ISSUE TITLE
Settings folder should be configurable

### ISSUE THREAD

**Issue by gflegar** [GPUOpen-Drivers/xgl#117]
In some situations, the settings folder that XGL reads its settings files from (`/etc/amd`) is not ideal. For instance, during development or testing when those settings should be changed, modifying files in `/etc/amd` would require root access. The folder used to read the settings files from should instead be made configurable (e.g., via an environment variable).

**Comment by Flakebi** [comment]
Just for completeness, using `~/.config/amdVulkanSettings.cfg` does work (if `/etc/amd/amdVulkanSettings.cfg` does not exist).

**Comment by gflegar** [comment]
But as you mentioned, the driver only tries that if the global file does not exist, so it's no use when you want to override the global settings.

**Comment by gflegar** [comment]
Looking a bit more into the code, there is the [AMD_CONFIG_DIR](https://github.com/GPUOpen-Drivers/pal/blob/dev/inc/util/palSettingsFileMgrImpl.h#L58) variable, which should do this exact thing.
