### ISSUE TITLE
Switchable graphics layer filters out cards AMDVLK dropped support for

### ISSUE THREAD

**Issue by Joshua-Ashton** [GPUOpen-Drivers/xgl#126]
AMDVLK dropped support for pre-Polaris at some point.

The switchable graphics layer shouldn't filter out these cards because they're still supported in RADV.

Right now, if a user installs AMDVLK by accident, or upgrades AMDVLK and finds their card no longer supported, they can no longer use Vulkan on their system.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/5196#note_1023202

**Comment by jinjianrong** [comment]
@Joshua-Ashton  the issue is fixed with v-2021.Q3.6. Please check it
