### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Drivers/xgl#14]
I would like to point out that identifiers like “[`__COLOR_SPACE_HELPER_H__`](https://github.com/GPUOpen-Drivers/xgl/blob/a63c42b81cadf19c1e65ae5ad9d25d0c6b2af162/icd/api/include/color_space_helper.h#L32)” and “[`__VK_CMDBUFFER_H__`](https://github.com/GPUOpen-Drivers/xgl/blob/a63c42b81cadf19c1e65ae5ad9d25d0c6b2af162/icd/api/include/vk_cmdbuffer.h#L32)” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by linqunzju** [comment]
Thank you for your comments. but I am afraid we can't remove these completely. some header files are imported from other components, we don't plan to modify it.
I think we can remove all header guards in folder api/include, #pragma once is enough for us.

**Comment by elfring** [comment]
I suggest to [rename questionable identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by linqunzju** [comment]
address lib and hardware header files are not maintained by us. we just imported them. so we can't change them :(.

**Comment by elfring** [comment]
Can these external software components be also [fixed anyhow](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by linqunzju** [comment]
I am not sure. even it can, I am afraid I can't be done in short time.
