### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Drivers/xgl#15]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ShaderMerger::BuildEsGsMergedShader](https://github.com/GPUOpen-Drivers/xgl/blob/33401094c5d4fe48c034d9ba8f611f2bd3646e93/icd/api/llpc/patch/gfx9/llpcShaderMerger.cpp#L196 "ShaderMerger::BuildEsGsMergedShader function")
- [ShaderMerger::BuildLsHsMergedShader](https://github.com/GPUOpen-Drivers/xgl/blob/33401094c5d4fe48c034d9ba8f611f2bd3646e93/icd/api/llpc/patch/gfx9/llpcShaderMerger.cpp#L132 "ShaderMerger::BuildLsHsMergedShader function")

**Comment by linqunzju** [comment]
I agree, it is not necessary. we will review whole llpc folder and  fix it step by step after Chinese New Year. 
of course, I will be appreciate if you can help to fix it :)

**Comment by JacobHeAMD** [comment]
Will not fix, keep them for safe

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
