### ISSUE TITLE
amdvlk shouldn't enable NoSignedZeros option

### ISSUE THREAD

**Issue by airlied** [GPUOpen-Drivers/xgl#16]
From the spec:

Precision and Operation of SPIR-V Instructions

The following rules apply to both single and double-precision floating point instructions:

    Positive and negative infinities and positive and negative zeros are generated as dictated by IEEE 754, but subject to the precisions allowed in the following table.

We've faced the same issue in radv, and the spec seems quite clear on it.

**Comment by linqunzju** [comment]
It is to get better performance. we will disable it once we found any test dependent on this feature or llvm back-end provide a new option to enable modifier div:2 and mul:2.

**Comment by JacobHeAMD** [comment]
Will not fix
