### ISSUE TITLE
Incorrect assertion for `VkRenderPassAttachmentBeginInfo` with a non-imageless `VkFramebuffer`

### ISSUE THREAD

**Issue by glebov-andrey** [GPUOpen-Drivers/xgl#164]
When running my application with a debug build of AMDVLK, I get an assertion here:
https://github.com/GPUOpen-Drivers/xgl/blob/0387177d6143533c88ff0d5ac045bf3994ee618b/icd/api/vk_cmdbuffer.cpp#L7911

`vkCmdBeginRenderPass` is being called with a normal non-imageless `VkFramebuffer`, and the `VkRenderPassBeginInfo` chain contains a `VkRenderPassAttachmentBeginInfo` structure with its `attachmentCount == 0`.
This is explicitly permitted by the spec for non-imageless framebuffers [here](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03207):

> If `framebuffer` was created with a `VkFramebufferCreateInfo::flags` value that did not include `VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT`, and the `pNext` chain includes a `VkRenderPassAttachmentBeginInfo` structure, its `attachmentCount` **must** be zero.

It looks like the following call to `SetImageViews(pRenderPassAttachmentBeginInfo)` doesn't actually do anything when `attachmentCount == 0`, so this is probably just an incorrect assertion.

**Comment by jinjianrong** [comment]
Fixed in 2023.Q1.1
