### ISSUE TITLE
No Support for VK_EXT_graphics_pipeline_library on windows

### ISSUE THREAD

**Issue by Abdelrahman-7gab** [GPUOpen-Drivers/xgl#171]
The VK_EXT_graphics_pipeline_library extension has been around in Nvidia GPUs for a while and also in AMD RADV but not in AMD Windows yet. it's a very important extension as it completely fixes the stutters while loading shaders in some games and also very important for the use of dxvk on windows.

please let us know if any updates towards supporting this extension is going to happen soon

**Comment by oscarbg** [comment]
+1, altough may be better to ask on main amdvlk repo..

**Comment by oscarbg** [comment]
Also related VK_EXT_shader_object can help reducing stuttering if used by apps..

**Comment by stanlu1013** [comment]
i ask at AMD community.

https://community.amd.com/t5/opengl-vulkan/please-add-this-vk-extension-vk-ext-graphics-pipeline-library/m-p/602757#M4670

**Comment by koffiato** [comment]
I've made another thread about this https://community.amd.com/t5/newcomers-start-here/vk-ext-graphics-pipeline-library-still-isn-t-here/m-p/630210#M2770

**Comment by amdrexu** [comment]
We are working on this extension. And we want to do more internal experiments both in correctness aspect and in performance aspect to make the design optimal before exposing it.

**Comment by koffiato** [comment]
Updating this issue here too. Time frame is ridiculous.

**Comment by jinjianrong** [comment]
The extension is supported now
