### ISSUE TITLE
vkQueueSubmit2 does not respect VkCommandBufferSubmitInfo::deviceMask

### ISSUE THREAD

**Issue by RogueLogix** [GPUOpen-Drivers/xgl#173]
The deviceMask component of VkCommandBufferSubmitInfo isn't read by Queue::Submit, only the device mask from VkDeviceGroupSubmitInfo for vkQueueSubmit is read from. The submit instead behaves as if every device mask is `1` for only the primary/first GPU. This includes a devicemask of zero, which for vkQueueSubmit2 means execute on all devices, unlike a lack of VkDeviceGroupSubmitInfo meaning primary only.

**Comment by Reger95** [comment]
Hi RogueLogix, can you provide me the source code with this issue?  Thanks~

**Comment by jinjianrong** [comment]
Fixed in 2024.Q3.1
