### ISSUE TITLE
vkQueueSubmit/vkQueueSubmit2 returns VK_TIMEOUT when non-primary GPU is asked to wait on non-signaled timeline semaphore.

### ISSUE THREAD

**Issue by RogueLogix** [GPUOpen-Drivers/xgl#174]
When using a timeline semaphore that will be signaled from the same thread after submit [this line in vk_queue.cpp](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/vk_queue.cpp#1469) (and potentially others, but thats where i found it to be happening when debugging) can have a PAL timeout returned, causing the function to early out and return the invalid for vkQueueSubmit/vkQueueSubmit2 return code of VK_TIMEOUT. The timeout does also cause other spec compliance issues, but they appear to all be the result of the underlying timeout.

Does require a signal operation in the same submit, but only presents itself when the wait semaphore is not yet signaled. Presence or lack of command buffer submit does not appear to affect the result

Produced using a device group of two W5700 GPUs on Ubuntu 22.04 through vkQueueSubmit2, with a timeline semaphore wait executed on device index 1 for a semaphore that will be signaled after submit. The same operation with device index 0 completes as expected after signaling on the host. When used in a single device device group, both physical devices behave correctly.

If needed i can provide code that reproduces the issue on my machine.

**Comment by RogueLogix** [comment]
Found root cause, Semaphore::PopulateInDeviceGroup doesn't carry the timeline flag to the other device semaphores, causing the second device to not stall its queue correctly.

**Comment by lukelmy** [comment]
Hi RogueLogix, could you pls provide the source code? Thanks!

**Comment by RogueLogix** [comment]
heres a gist with a minimal repro cpp file, as well as the patch of what i did locally to fix it
https://gist.github.com/RogueLogix/6583dddb1a5aa1e7384d0390d87ad290

**Comment by jinjianrong** [comment]
This is fixed in recent releases
