### ISSUE TITLE
Verification error using R32ui image format

### ISSUE THREAD

**Issue by alan-baker** [GPUOpen-Drivers/xgl#20]
```
ERROR: Fails to verify module (llpc-pass-external-lib-link): Invalid bitcast
  %1 = bitcast i32 %texel to <4 x float>
```
Shader generated from HLSL through DXC: [test.spvas.txt](https://github.com/GPUOpen-Drivers/xgl/files/1877401/test.spvas.txt)

The image format is R32ui, but all the library functions for image writes seem to expect four component vectors (from g_glslImageOpEmu.ll):
```
define void @llpc.image.write.u32.Buffer(i32 %resourceDescSet, i32 %resourceBinding, i32 %resourceIdx ,i32 %coord ,<4 x i32> %texel ,i1 %glc ,i1 %slc ,i32 %imageCallMeta) #1
{
    %resource = call <4 x i32> @llpc.descriptor.load.texelbuffer(i32 %resourceDescSet, i32 %resourceBinding, i32 %resourceIdx)
    %1 = bitcast <4 x i32> %texel to <4 x float>
    call void @llvm.amdgcn.buffer.store.format.v4f32(<4 x float> %1, <4 x i32> %resource, i32 %coord, i32 0, i1 %glc, i1 %slc)
    ret void 
}
```
That image write is invoked in the shader as:
```
  call void @llpc.image.write.u32.Buffer(i32 4, i32 69, i32 0, i32 %6, i32 64, i1 false, i1 false, i32 326) #0
```

The `texel` operand has a mismatched type.

**Comment by linqunzju** [comment]
Reproduced, I agree it is our driver's bug. we will fix it ASAP.

**Comment by jinjianrong** [comment]
@alan-baker A fix is included in today's code drop, could you please give it a try?  Thanks.
