### ISSUE TITLE
Pipeline compilation failure When running ManiaPlanet under Wine

### ISSUE THREAD

**Issue by libcg** [GPUOpen-Drivers/xgl#21]
When running ManiaPlanet under Wine with DXVK and amdvlk 9e6992f, I'm getting some pipeline compilations failures.

SPIR-V dumps are available here: http://dl.free.fr/bWMhdEP08

**Comment by jinjianrong** [comment]
@libcg, we had a fix in latest code, please give it a try.  thanks for reporting the issue.

**Comment by libcg** [comment]
I can confirm that all those shaders are compiling now. The menu renders perfectly now. However I'm getting a GPU hang when going ingame.

**Comment by libcg** [comment]
Still hitting the hang with 67fcf19

**Comment by libcg** [comment]
Looks like the hang is solved with ef2ad11, however I'm getting some graphical glitches on some surfaces:
![screenshot from 2018-05-14 21-24-11](https://user-images.githubusercontent.com/490159/40036596-3a62e3da-57bd-11e8-8810-75159b0a635d.png)

RADV has the exact same issue, so it must be a LLVM problem. @jinjianrong

**Comment by libcg** [comment]
Here's an apitrace http://dl.free.fr/kMtoyObC2 you should be able to replay it using https://people.freedesktop.org/~jrfonseca/apitrace/apitrace-msvc-latest.7z

**Comment by jinjianrong** [comment]
@libcg  would you mind closing this issue and create a new issue for the graphical glitches

**Comment by libcg** [comment]
Sure thing.

**Comment by crystalJinamd** [comment]
@libcg Which game are you running on ManiaPlanet, Trackmania² Stadium, Trackmania² Canyon, Trackmania² Valley, Trackmania² Lagoon or others ?

**Comment by libcg** [comment]
I only own Stadium
