### ISSUE TITLE
VK_EXT_vertex_attribute_divisor support

### ISSUE THREAD

**Issue by libcg** [GPUOpen-Drivers/xgl#23]
This extension will be required by https://github.com/doitsujin/dxvk to efficiently support instancing step rates. It's already exposed by latest RADV and nvidia drivers.

**Comment by doitsujin** [comment]
This extension is now a hard requirement for DXVK and is supported on RADV.

**Comment by jinjianrong** [comment]
The extension has been implemented in internal branch, will be released soon.

**Comment by oscarbg** [comment]
Any update? We have been almost three weeks without updates..

**Comment by libcg** [comment]
This apparently landed in 3cf9e93c. Closing.
