### ISSUE TITLE
sample mask input to fs shouldn't force persample execution

### ISSUE THREAD

**Issue by airlied** [GPUOpen-Drivers/xgl#3]
From my reading of the spec, using gl_SampleId or gl_SamplePosition should force per sample execution, however the spec doesn't seem to mention the gl_SampleMask input causing per sample.

AMDVLK sets  m_pResUsage->builtInUsage.fs.runAtSampleRate for gl_SampleMask.

**Comment by cainguo** [comment]
I didn't see AMDVLK sets m_pResUsage->builtInUsage.fs.runAtSampleRate for gl_SampleMask, but only for gl_SampleMaskIn.

**Comment by Kai-AMD** [comment]
Hi Airlied,

We are now working on this issue.

Thanks for your help!

Best Regards,
Kai

**Comment by jinjianrong** [comment]
Fix is merged to master branch
