### ISSUE TITLE
shaderdb test Ext16bitStorage_TestTesOutput.tese hits infinite loop

### ISSUE THREAD

**Issue by alan-baker** [GPUOpen-Drivers/xgl#31]
When I run the shaderdb test Ext16bitStorage_TestTesOutput.tese, it hits an infinite loop in the DAG combiner during backend code generation.

**Comment by linqunzju** [comment]
I suppose you run this test with gfxip = 9, it is a known issue, we will fix it ASAP.

**Comment by jinjianrong** [comment]
@alan-baker The issue is fixed in latest LLVM, please try it.
