### ISSUE TITLE
vkGetPhysicalDeviceXlibPresentationSupportKHR returns false when presentation is supported

### ISSUE THREAD

**Issue by edrickhong** [GPUOpen-Drivers/xgl#32]
This is as of the latest build on Github. Fedora 28

**Comment by JacobHeAMD** [comment]
Hi @edrickhong , do you mind to help do a little debug? Could you please help to check if Dri3WindowSystem::IsDevicePresentable returns true? If not, could you please check what is pPciBusString? Thanks in advance!

**Comment by edrickhong** [comment]
Just to be clear, a valid pProvidersReply is returned. num_providers is 0

**Comment by JacobHeAMD** [comment]
Got it, thanks!

**Comment by edrickhong** [comment]
I almost forgot. If it helps, this is also running under XWayland, not X11 directly
