### ISSUE TITLE
Mismatch of OpName on entry point and OpEntryPoint name causes crash

### ISSUE THREAD

**Issue by baldurk** [GPUOpen-Drivers/xgl#4]
When compiling compile a shader where the `OpEntryPoint` declares one string - matching the `VkPipelineShaderStageCreateInfo` name, but the entry point has an `OpName` of a different string, the pipeline compile crashes.

The code that identifies the SPIR-V function that is the entry point we want is [here in `SPIRVToLLVM::translate`](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/llpc/translator/SPIRVReader.cpp#L2978-L2987).

```cpp
  // Find the targeted entry-point in this translation
  for (unsigned I = 0, E = BM->getNumFunctions(); I != E; ++I) {
    auto BF = BM->getFunction(I);
    ExecutionModel ExecModel = ExecutionModelMax;
    bool IsEntry = BM->isEntryPoint(BF->getId(), &ExecModel);
    if (IsEntry && ExecModel == EntryExecModel && BF->getName() == EntryName) {
      EntryTarget = BF;
      break;
    }
  }
```

However `getName()` returns the `OpName` - it should be checking only against the declared entry point name. Consider that even if there isn't a mismatch, there could be an entry point declared earlier with a different "entry point name", but with the OpName we are searching for - OpName can be _anything_ including duplicated.

Note that if there is no `OpName` at all for the entry point ID, then everything works for me.

Minimal repro compute shader SPIR-V that will crash when passed to `vkCreateComputePipelines` with appropriate boiler-plate pointing to entry point "rdc":

```asm
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %not_rdc "rdc"
               OpExecutionMode %not_rdc LocalSize 128 1 1
               OpName %main "main"
               OpName %not_rdc "not_rdc"
       %void = OpTypeVoid
          %4 = OpTypeFunction %void
       %main = OpFunction %void None %4
          %5 = OpLabel
               OpReturn
               OpFunctionEnd
    %not_rdc = OpFunction %void None %4
          %6 = OpLabel
          %7 = OpFunctionCall %void %main
               OpReturn
               OpFunctionEnd
```

If you remove the `OpName %1(not_rdc) "not_rdc"` it will work OK.

FYI I ran into this on amdvlk as built from latest of today (GPUOpen-Drivers/pal@91e30f14e0903aeed35604382e4fa5b41f027125, GPUOpen-Drivers/xgl@3e2d125e523ad0b748f52907165054b63ad21425, GPUOpen-Drivers/llvm@eb5eb1c6b6f21677a9a8f026eb6bd20b1ec59815).

**Comment by linqunzju** [comment]
Yes, it is a bug in SPIRV decode.  we don't record entry point name correctly in SPIRVModule. (SPIRVEntryPoint::decode)
we will fix it ASAP.

ps: which disassemble tool did you use? It seems this style isn't accepted by spirv-tools.

**Comment by baldurk** [comment]
Sorry that's my fault - I had some local hacks to spirv-dis to print the name and ID, when I was doing some hacking on SPIR-V (by default it can only show one or the other). I've edited the original post with canonical disassembly.

**Comment by jinjianrong** [comment]
@baldurk  please try the fix https://github.com/GPUOpen-Drivers/xgl/commit/0e5197e628ce3bc7b58ff8137649850ec92acf06

**Comment by jinjianrong** [comment]
@baldurk please try the fix https://github.com/GPUOpen-Drivers/xgl/commit/f49b3d804de218a3d8506c7b5bf70cded930be21

**Comment by jinjianrong** [comment]
The fix is mergered to master branch
