### ISSUE TITLE
Documentation for guards using `LLPC_CLIENT_INTERFACE_MAJOR_VERSION`

### ISSUE THREAD

**Issue by jaebaek** [GPUOpen-Drivers/xgl#69]
`LLPC_CLIENT_INTERFACE_MAJOR_VERSION` helps us avoid build failures when we use the old XGL with the new LLPC.

### 1.
In my opinion, if a document briefly explained the rule, it would be helpful to understand the context.

### 2.
In addition, I am still confused how to quickly check the next `LLPC_CLIENT_INTERFACE_MAJOR_VERSION` number.
If there was a specific file somewhere contains the next number, it would be helpful.
Please let me know if I missed the already existing file for it.

**Comment by kuhar** [comment]
Related: PAL/XGL versioning https://github.com/GPUOpen-Drivers/pal/pull/51#issuecomment-724330518

**Comment by Flakebi** [comment]
Regarding 2: The main header file [vkgcDefs.h](https://github.com/GPUOpen-Drivers/llpc/blob/dev/include/vkgcDefs.h#L73) has a history of all versions. Any change that increments the version number adds a line there.
